### ISSUE TITLE
Civil Disorder VPs not awarded

### ISSUE THREAD

**Issue by Silver1974** [EaW1805/engine#20]
Game 31, Italy. Rhine declared war vs Italy on September 1803, went into CD April 1804, VPs not awarded
Game 28, Rhine. Prussia declared war on November 1805, went into CD July 1806, VPs not awarded.

Makis note: others seems to get the VPs in the same games, but _they_ declared war on the nations that go into CD. Could it be that the effect is triggered only when you declare on someone, not when you are declared upon by the nation going into CD?

**Comment by ichatz** [comment]
In order to gain VPs from a CD you need to be in war for 8 months.

Game 31: Italy
September 1803 -> April 1804: 8 months
-> No VPs allocated - this is wrong.

Game 28: Rhine
November 1805 -> July 1806: 9 months
-> 30 VPs allocated as stated in newsletter
check out here:
http://www.eaw1805.com/report/scenario/1802/game/28/nation/2/month/51

The code has been corrected - it was checking for 9 months instead of 8.
